baseurl = "http://healthsquare.com.au/"
languageCode = "en-us"
newContentEditor = "nano"
pygmentsStyle = "native"
theme = "hugo-phlat-theme"
title = "Healthsquare"
canonifyurls = true
[[menu.footer]]
name = "About"
url = "/about/"
weight = 1
[[menu.footer]]
name = "Advertise"
url = "/advertise/"
weight = 2
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 3
[[menu.footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 4
[[menu.header]]
name = "Home"
url = "/"
weight = 1
[[menu.header]]
name = "Resources"
url = "/resources/"
weight = 2
[params]
description = "Innovation and opportunities in primary care"
disqus = "site_name_here"
google_adsense = "ca-pub-XXXXXXXX"
google_analytics = "UA-XXXXXXX-YY"
googleplus = ""
keywords = ["default", "keywords", "if", "no", "front", "matter"]
linkedin = ""
paypal = ""
twitter = "https://www.twitter.com/"
youtube = ""
[permalinks]
page = "/:title/"
resource = "/section/:slug/"
news = "/:section/:year/:month/:day/:slug/"
[taxonomies]
category = "categories"
tag = "tags"
ignoreFiles = [ "\\.foo$", "\\.boo$" ]
[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]
