baseurl = "/"
languageCode = "en-us"
newContentEditor = "nano"
pygmentsStyle = "native"
theme = "hugo-phlat-theme"
title = "HEALTHSquare"
canonifyurls = true

[[menu.footer]]
name = "Home"
url = "/"
weight = 1


[[menu.footer]]
name = "About"
url = "/about/"
weight = 3
[[menu.footer]]
name = "Advertise"
url = "/advertise/"
weight = 4
[[menu.footer]]
name = "Contact"
url = "/contact/"
weight = 5
[[menu.footer]]
name = "Subscribe"
url = "/subscribe/"
weight = 6
[[menu.footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 7

[params]
description = "New business opportunities in primary care"
disqus = "site_name_here"
google_adsense = "ca-pub-XXXXXXXX"
google_analytics = "UA-XXXXXXX-YY"
googleplus = ""
keywords = ["default", "keywords", "if", "no", "front", "matter"]
linkedin = ""
paypal = ""
twitter = "https://www.twitter.com/"
youtube = ""
[permalinks]
page = "/:slug/"
post = "/news/:year:month:day/:slug/"
[taxonomies]
category = "categories"
tag = "tags"
ignoreFiles = [ "\\.foo$", "\\.boo$" ]
[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  extensions = ["hardLineBreak"]
