baseurl = "https://www.healthsquare.com.au"
languageCode = "en-us"
newContentEditor = "nano"
pygmentsStyle = "native"
theme = "hugo-phlat-theme"
title = "Healthsquare"
[[menu.footer]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 1
[[menu.footer]]
name = "Sponsors"
url = "/sponsors/"
weight = 2
[[menu.header]]
name = "Home"
url = "/"
weight = 1
[[menu.header]]
name = "Resources"
url = "/resources/"
weight = 2
[[menu.header]]
name = "Contact"
url = "/contact/"
weight = 3
[params]
description = "Innovation and business opportunities "
disqus = "site_name_here"
google_adsense = "ca-pub-XXXXXXXX"
google_analytics = "UA-XXXXXXX-YY"
googleplus = ""
keywords = ["default", "keywords", "if", "no", "front", "matter"]
linkedin = ""
paypal = ""
twitter = "https://www.twitter.com/"
youtube = ""
[permalinks]
page = "/:slug/"
post = "/:year/:month/:slug/"
[taxonomies]
category = "categories"
tag = "tags"
